### ISSUE TITLE
Inject not works after global maintenance?

### ISSUE THREAD

**Issue by Jhonvf20** [shalzuth/BraveHaxvius#26]
Hi, I can't use the inject tool. I Compile and generates the .exes files. Run and execute the injection. It seems to finish the mission correctly, but the items are not injected.

**Comment by firefist8** [comment]
injection patched. No longer possible. Its sad but I will not work anymore.

**Comment by Jhonvf20** [comment]
@firefist8 I will work on this. What can i do? analyze the packages or get the keys back?

**Comment by firefist8** [comment]
I mean it will not work anymore. I dont know any details but people say injection wont be possible anymore. Unless someone finds a new way.

**Comment by refoz** [comment]
Hey man, can you teach me how to use the gun? I will donate to you on paypal but I could not use the program ... if you can, send me an email eo.renandesouza@gmail.com

**Comment by OGVENDETTA** [comment]
@firefist8 Injections patched. No more Injections.
@refoz You're on the wrong website. This is for programming not selling firearms.

**Comment by refoz** [comment]
Sorry i write wrong, i use the translate, i want say that i dont how inject, i download Fiddler, but i dont know what i do now... if can u teach me, i will donate for u, send me an email eo.renandesouza@gmail.com

**Comment by Jhonvf20** [comment]
@refoz Like @OGVENDETTA says... it's patched.

**Comment by Reosann** [comment]
Hi, I'm not really an expert but.. If i got it right, injection were related to missions. They patched that, so it's needed to find a new way. What about messages? Is it possible to inject using that? Maybe making exvius thinking that are mission rewards (like use black magic and so on)? Or also a daily quest completed or rookie quest... Is it possible?

**Comment by senaia1** [comment]
Injection was possible because trust rewards after battle weren't checked with the server. Drops in battle, chests and loot spots in exploration areas, items from dailies and the inbox are all predetermined items checked with the server. Since gumi decided to start doing the server check on trust items, at the moment there's no way to inject.
Future possibilities could include items from raid summon coins, but I'm pretty sure they're gonna have a server check... Won't know for certain until the next raid. As such, this shouldn't be marked as an issue... It's just a feature that doesn't work anymore for global

**Comment by Reosann** [comment]
Then, what about make the app connect to a custom server, just for the check, and then connect to the normal server for validating injection?

**Comment by WillyoWisp** [comment]
I would guess the issue there is that Gumi's server will still have the latest data for your account, which is what would be used.

**Comment by shalzuth** [comment]
injection fixed.
